FROM ubuntu:22.04
COPY *.deb /
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get install -y curl pgp ninja-build libssl-dev && \
    curl -L https://apt.llvm.org/llvm-snapshot.gpg.key |  apt-key add - && \
    echo 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main' | tee /etc/apt/sources.list.d/llvm.list >/dev/null && \
    apt-get update -y && \
    apt-get install -y clang-13 cmake libclang-13-dev lld-13 libc++-13-dev libc++abi-13-dev && \
    apt-get install -y /*.deb && \
    update-alternatives --install /usr/bin/cc cc /usr/lib/llvm-13/bin/clang 50 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/lib/llvm-13/bin/clang++ 50 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
